#!/bin/sh

PACKAGE=unison
VERSION=$2
ORIG=$1

set -e 

if test -d $PACAKGE-$VERSION; then
	echo "Directory $PACKAGE-$VERSION exists"
	exit 1
fi
	

tar xzf $ORIG

rm -f $PACKAGE-$VERSION/mt/threads.obj
rm -f $PACKAGE-$VERSION/non-mt/threads.cmi
rm -f $PACKAGE-$VERSION/non-mt/threads.cmx
rm -f $PACKAGE-$VERSION/non-mt/threads.o
rm -f $PACKAGE-$VERSION/non-mt/threads.obj
rm -f $PACKAGE-$VERSION/win32rc/unison.res
rm -f $PACKAGE-$VERSION/win32rc/unison.res.lib

chmod 644 $PACKAGE-$VERSION/INSTALL
chmod 644 $PACKAGE-$VERSION/Makefile.OCaml
chmod 644 $PACKAGE-$VERSION/ubase/uprintf_new.ml
chmod 644 $PACKAGE-$VERSION/ubase/uprintf_old.ml

tar czf $ORIG $PACKAGE-$VERSION/
rm -rf $PACKAGE-$VERSION
